language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install pytest coverage coveralls
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install unittest2
  - pip install -r requirements.txt
  - pip install scipy astropy
  - pip install .

# command to install dependencies
script:
  - cd tests; coverage run --source=hickle -m py.test

after_success: coveralls

branches:
  only:
    - dev
