language: python
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install pytest coveralls
  - pip install --only-binary=numpy,scipy numpy scipy==1.1.0
  - pip install -r requirements.txt
  - pip install .

script:
  - python setup.py test

# Run code coverage
after_success: coveralls

# Run on dev and master branches
branches:
  only:
    - dev
    - master
