language: python
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements_test.txt
  - pip install .

script:
  - python setup.py test

# Run code coverage
after_success: coveralls
