language: python
python:
  - "2.7"
  #- "3.4"
  - "3.5"
  - "3.6"

# Add Python 3.7 support
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install pytest coveralls
  - pip install --only-binary=numpy
  - pip install -r requirements.txt
  - pip install .

# command to install dependencies
script:
  - python setup.py test

# Run code coverage
after_success: coveralls

# Run on dev and master branches
branches:
  only:
    - dev
    - master
