language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install unittest2
  - pip install -r requirements.txt
  - pip install .

# command to install dependencies
script: python tests/test_hickle.py
branches:
  only:
    - dev
